CREATE COLUMN TABLE "Employees" (
     "EMPLOYEEID" INTEGER NOT NULL COMMENT 'Employee ID',
	 "NAME.FIRST" VARCHAR(40) COMMENT 'First or Given Name',
	 "NAME.MIDDLE" VARCHAR(40) COMMENT 'Middle Name',
	 "NAME.LAST" VARCHAR(40) COMMENT 'Family Name',
	 "NAME.INITIALS" NVARCHAR(10) COMMENT 'Initials',
	 "SEX" NVARCHAR(1) COMMENT 'Gender',
	 "LANGUAGE" NVARCHAR(1) COMMENT 'Primary Spoken Language',
	 "PHONENUMBER" NVARCHAR(30) COMMENT 'Primary Phone Number',
	 "EMAILADDRESS" NVARCHAR(255) COMMENT 'Email Address',
	 "LOGINNAME" NVARCHAR(12) COMMENT 'Login Username',
	 "ADDRESSES.ADDRESSID" INTEGER  COMMENT 'Address Association',
	 "VALIDITY.STARTDATE" DATE  COMMENT 'Start Date',
	 "VALIDITY.ENDDATE" DATE  COMMENT 'End Date',
	 "CURRENCY" NVARCHAR(5) COMMENT 'Document Currency',
	 "SALARYAMOUNT" DECIMAL(15,	2)  COMMENT 'Salary Amount',
	 "ACCOUNTNUMBER" NVARCHAR(10) COMMENT 'Bank Account Number',
	 "BANKID" NVARCHAR(10) COMMENT 'Bank ID',
	 "BANKNAME" NVARCHAR(255) COMMENT 'Bank Name',
	 "EMPLOYEEPICURL" NVARCHAR(255) COMMENT 'Employee Picture URL',
	 PRIMARY KEY ("EMPLOYEEID")) 
	 WITH ASSOCIATIONS( JOIN "Addresses" AS "ADDRESSES" ON "ADDRESSES"."ADDRESSID" = "ADDRESSES.ADDRESSID") 
	 COMMENT 'Employees'
	 UNLOAD PRIORITY 5 AUTO MERGE 