CREATE COLUMN TABLE "Header" (
    "PURCHASEORDERID" INTEGER NOT NULL COMMENT 'Purchase Order ID',
    "HISTORY.CREATEDBY.EMPLOYEEID" INTEGER  COMMENT 'Created By',
    "HISTORY.CREATEDAT" DATE  COMMENT 'Created Date',
    "HISTORY.CHANGEDBY.EMPLOYEEID" INTEGER  COMMENT 'Last Updated By',
    "HISTORY.CHANGEDAT" DATE  COMMENT 'Last Update Date',
    "NOTEID" NVARCHAR(10) COMMENT 'Notes',
    "PARTNER.PARTNERID" INTEGER  COMMENT 'Partner Association',
    "CURRENCY" NVARCHAR(5) COMMENT 'Currency',
    "GROSSAMOUNT" DECIMAL(15,2)  COMMENT 'Gross Amount',
    "NETAMOUNT" DECIMAL(15,2)  COMMENT 'Net Amount',
    "TAXAMOUNT" DECIMAL(15,2)  COMMENT 'Tax Amount',
    "LIFECYCLESTATUS" NVARCHAR(1) COMMENT 'Lifecycle Status',
    "APPROVALSTATUS" NVARCHAR(1) COMMENT 'Approval Status',
    "CONFIRMSTATUS" NVARCHAR(1) COMMENT 'Confirmation Status',
    "ORDERINGSTATUS" NVARCHAR(1) COMMENT 'Ordering Status',
    "INVOICINGSTATUS" NVARCHAR(1) COMMENT 'Invoicing Status',
    PRIMARY KEY ("PURCHASEORDERID")) 
    WITH ASSOCIATIONS( JOIN "Employees" AS "HISTORY.CHANGEDBY" ON "HISTORY.CHANGEDBY"."EMPLOYEEID" = "HISTORY.CHANGEDBY.EMPLOYEEID",
                       JOIN "Employees" AS "HISTORY.CREATEDBY" ON "HISTORY.CREATEDBY"."EMPLOYEEID" = "HISTORY.CREATEDBY.EMPLOYEEID",
                       JOIN "Item" AS "ITEMS" ON "PURCHASEORDERID" = "PURCHASEORDERID",
                       JOIN "BusinessPartner" AS "PARTNER" ON "PARTNER"."PARTNERID" = "PARTNER.PARTNERID") 
    COMMENT 'Purchase Order Header'
    UNLOAD PRIORITY 5 AUTO MERGE 